CREATE TABLE contrys (
    ID INTEGER AUTOINCREMENT PRIMARY KEY,
    name_contry TEXT NOT NULL UNIQUE,
    img TEXT NOT NULL 
);

CREATE TABLE users(
    ID INTEGER AUTOINCREMENT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT,
    points INTEGER DEFAULT 0
);